function school(id, extra) {
  return {
    _id: id,
    website: 'https://www.example.edu.cn',
    jianjie: '院校简介',
    jianjie_neirong: extra.jianjie_neirong || `${extra.schoolname}是我国重要的高等教育机构，学科门类齐全，研究生培养体系完善。`,
    lingdao: '现任领导',
    lingdao_neirong: '党委书记、校长等信息以学校官网为准。',
    huanjing: '校园环境',
    huanjing_neirong: '校园设施完善，适合研究生学习和生活。',
    ...extra
  };
}

function major(id, extra) {
  return {
    _id: id,
    exam_style: '统考',
    learn_type: '全日制',
    language: '英语一',
    political: '思想政治理论',
    enrollment: '20',
    class1: '数学一',
    class2: '专业课',
    ...extra
  };
}

const yx = [
  school('yx_pku', { schoolname: '北京大学', schooladdress: '北京', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_thu', { schoolname: '清华大学', schooladdress: '北京', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_zju', { schoolname: '浙江大学', schooladdress: '浙江', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_fudan', { schoolname: '复旦大学', schooladdress: '上海', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_sjtu', { schoolname: '上海交通大学', schooladdress: '上海', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_nju', { schoolname: '南京大学', schooladdress: '江苏', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_hust', { schoolname: '华中科技大学', schooladdress: '湖北', belong: '教育部', title: '211985', type: '工科' }),
  school('yx_buaa', { schoolname: '北京航空航天大学', schooladdress: '北京', belong: '工业与信息化部', title: '211985', type: '工科' }),
  school('yx_bupt', { schoolname: '北京邮电大学', schooladdress: '北京', belong: '教育部', title: '211', type: '工科' }),
  school('yx_neu', { schoolname: '东北大学', schooladdress: '辽宁', belong: '教育部', title: '211985', type: '工科' }),
  school('yx_xjtu', { schoolname: '西安交通大学', schooladdress: '陕西', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_ustc', { schoolname: '中国科学技术大学', schooladdress: '安徽', belong: '中国科学院', title: '211985', type: '工科' }),
  school('yx_whu', { schoolname: '武汉大学', schooladdress: '湖北', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_sysu', { schoolname: '中山大学', schooladdress: '广东', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_hit', { schoolname: '哈尔滨工业大学', schooladdress: '黑龙江', belong: '工业与信息化部', title: '211985', type: '工科' }),
  school('yx_scu', { schoolname: '四川大学', schooladdress: '四川', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_sdu', { schoolname: '山东大学', schooladdress: '山东', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_jlu', { schoolname: '吉林大学', schooladdress: '吉林', belong: '教育部', title: '211985', type: '综合' }),
  school('yx_hnu', { schoolname: '湖南大学', schooladdress: '湖南', belong: '教育部', title: '211', type: '工科' }),
  school('yx_zzu', { schoolname: '郑州大学', schooladdress: '河南', belong: '河南省教育厅', title: '211', type: '综合' }),
  school('yx_nwnu', { schoolname: '西北师范大学', schooladdress: '甘肃', belong: '甘肃省教育厅', title: '普通', type: '师范' })
];

const yx_more = [
  major('yxm_pku_cs', { schoolname: '北京大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '35', class2: '计算机专业基础综合' }),
  major('yxm_pku_se', { schoolname: '北京大学', major: '软件工程', major_num: '085405', menlei: '工学', yijixueke: '电子信息', enrollment: '28', class2: '软件工程综合' }),
  major('yxm_pku_ai', { schoolname: '北京大学', major: '人工智能', major_num: '0812J1', menlei: '工学', yijixueke: '计算机科学与技术', enrollment: '18', class2: '人工智能基础' }),
  major('yxm_thu_cs', { schoolname: '清华大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '40', class2: '计算机专业基础综合' }),
  major('yxm_thu_se', { schoolname: '清华大学', major: '软件工程', major_num: '085405', menlei: '工学', yijixueke: '电子信息', enrollment: '22', class2: '软件工程综合' }),
  major('yxm_zju_cs', { schoolname: '浙江大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '50', class2: '计算机专业基础综合' }),
  major('yxm_zju_ai', { schoolname: '浙江大学', major: '人工智能', major_num: '0812J1', menlei: '工学', yijixueke: '计算机科学与技术', enrollment: '24', class2: '人工智能基础' }),
  major('yxm_fudan_cs', { schoolname: '复旦大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '30' }),
  major('yxm_sjtu_se', { schoolname: '上海交通大学', major: '软件工程', major_num: '085405', menlei: '工学', yijixueke: '电子信息', enrollment: '32' }),
  major('yxm_nju_cs', { schoolname: '南京大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '26' }),
  major('yxm_hust_cs', { schoolname: '华中科技大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '45' }),
  major('yxm_buaa_cs', { schoolname: '北京航空航天大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '38' }),
  major('yxm_bupt_cs', { schoolname: '北京邮电大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '60' }),
  major('yxm_bupt_se', { schoolname: '北京邮电大学', major: '软件工程', major_num: '085405', menlei: '工学', yijixueke: '电子信息', enrollment: '42' }),
  major('yxm_neu_cs', { schoolname: '东北大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '36' }),
  major('yxm_xjtu_se', { schoolname: '西安交通大学', major: '软件工程', major_num: '085405', menlei: '工学', yijixueke: '电子信息', enrollment: '29' }),
  major('yxm_ustc_cs', { schoolname: '中国科学技术大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '20' }),
  major('yxm_whu_cs', { schoolname: '武汉大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '33' }),
  major('yxm_sysu_ai', { schoolname: '中山大学', major: '人工智能', major_num: '0812J1', menlei: '工学', yijixueke: '计算机科学与技术', enrollment: '16' }),
  major('yxm_hit_cs', { schoolname: '哈尔滨工业大学', major: '计算机技术', major_num: '085404', menlei: '工学', yijixueke: '电子信息', enrollment: '40' }),
  major('yxm_pku_phil', { schoolname: '北京大学', major: '马克思主义哲学', major_num: '010101', menlei: '哲学', yijixueke: '哲学', enrollment: '8', language: '英语一', class1: '哲学综合', class2: '马克思主义哲学' }),
  major('yxm_nju_phil', { schoolname: '南京大学', major: '马克思主义哲学', major_num: '010101', menlei: '哲学', yijixueke: '哲学', enrollment: '6', language: '英语一', class1: '哲学综合', class2: '马克思主义哲学' }),
  major('yxm_whu_phil', { schoolname: '武汉大学', major: '中国哲学', major_num: '010102', menlei: '哲学', yijixueke: '哲学', enrollment: '5', language: '英语一', class1: '哲学综合', class2: '中国哲学史' })
];

const zy_more = [
  {
    _id: 'zym_pku_cs',
    profession_name: '计算机技术',
    schoolname: '北京大学',
    direaction: '人工智能与系统软件',
    major_num: '085404',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '计算机技术',
    region: '北京',
    enrollment: '35',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_thu_cs',
    profession_name: '计算机技术',
    schoolname: '清华大学',
    direaction: '计算机系统结构',
    major_num: '085404',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '计算机技术',
    region: '北京',
    enrollment: '40',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_zju_cs',
    profession_name: '计算机技术',
    schoolname: '浙江大学',
    direaction: '智能计算与大数据',
    major_num: '085404',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '计算机技术',
    region: '浙江',
    enrollment: '50',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_bupt_cs',
    profession_name: '计算机技术',
    schoolname: '北京邮电大学',
    direaction: '网络与信息安全',
    major_num: '085404',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '计算机技术',
    region: '北京',
    enrollment: '60',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_hust_cs',
    profession_name: '计算机技术',
    schoolname: '华中科技大学',
    direaction: '计算机应用技术',
    major_num: '085404',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '计算机技术',
    region: '湖北',
    enrollment: '45',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_pku_se',
    profession_name: '软件工程',
    schoolname: '北京大学',
    direaction: '软件工程理论与方法',
    major_num: '085405',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '软件工程',
    region: '北京',
    enrollment: '28',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_sjtu_se',
    profession_name: '软件工程',
    schoolname: '上海交通大学',
    direaction: '工业软件与智能系统',
    major_num: '085405',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '软件工程',
    region: '上海',
    enrollment: '32',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_bupt_se',
    profession_name: '软件工程',
    schoolname: '北京邮电大学',
    direaction: '互联网软件工程',
    major_num: '085405',
    menlei: '工学',
    yijixueke: '电子信息',
    major: '软件工程',
    region: '北京',
    enrollment: '42',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_zju_ai',
    profession_name: '人工智能',
    schoolname: '浙江大学',
    direaction: '机器学习与计算机视觉',
    major_num: '0812J1',
    menlei: '工学',
    yijixueke: '计算机科学与技术',
    major: '人工智能',
    region: '浙江',
    enrollment: '24',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_sysu_ai',
    profession_name: '人工智能',
    schoolname: '中山大学',
    direaction: '智能科学与技术',
    major_num: '0812J1',
    menlei: '工学',
    yijixueke: '计算机科学与技术',
    major: '人工智能',
    region: '广东',
    enrollment: '16',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_pku_phil',
    profession_name: '马克思主义哲学',
    schoolname: '北京大学',
    direaction: '马克思主义哲学原理',
    major_num: '010101',
    menlei: '哲学',
    yijixueke: '哲学',
    major: '马克思主义哲学',
    region: '北京',
    enrollment: '8',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_nju_phil',
    profession_name: '马克思主义哲学',
    schoolname: '南京大学',
    direaction: '当代马克思主义',
    major_num: '010101',
    menlei: '哲学',
    yijixueke: '哲学',
    major: '马克思主义哲学',
    region: '江苏',
    enrollment: '6',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  },
  {
    _id: 'zym_whu_cphil',
    profession_name: '中国哲学',
    schoolname: '武汉大学',
    direaction: '中国近现代哲学',
    major_num: '010102',
    menlei: '哲学',
    yijixueke: '哲学',
    major: '中国哲学',
    region: '湖北',
    enrollment: '5',
    exam_style: '统考',
    language: '英语一',
    learn_type: '全日制',
    political: '思想政治理论'
  }
];

module.exports = { yx, yx_more, zy_more };
